name: Publish Package New

on:
  release:
    types:
      - published

# this needs to be better but also controlled.
env:
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore build/Kyameru.sln
    - name: Build
      run: dotnet build build/Kyameru.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/UnitTests/Kyameru.Tests/Kyameru.Tests.csproj --no-restore --verbosity normal
    - name: Output VERSION
      run: echo "${{ VERSION }}"
    #- name: Pack
    #  run: dotnet pack source/core/Kyameru.Core/Kyameru.Core.csproj -c Release -p:PackageVersion=$VERSION
    #- name: Push
    #  run: dotnet nuget push source/core/Kyameru.Core/bin/Release/Kyameru.Core.$VERSION.nupkg --api-key ${{ secrets.KYAMERU_NUGET }} -s https://api.nuget.org/v3/index.json
